# Generated by Django 2.0 on 2018-12-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('r_type', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
